-- MySQL Script generated by MySQL Workbench
-- Sun Jan  8 10:11:41 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema topmed_remapping
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema topmed_remapping
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `topmed_remapping` DEFAULT CHARACTER SET utf8 ;
USE `topmed_remapping` ;

-- -----------------------------------------------------
-- Table `topmed_remapping`.`statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `topmed_remapping`.`statuses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `topmed_remapping`.`compute_nodes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `topmed_remapping`.`compute_nodes` (
  `id` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `topmed_remapping`.`samples`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `topmed_remapping`.`samples` (
  `id` VARCHAR(64) NOT NULL,
  `status_id` INT UNSIGNED NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `compute_node_id` VARCHAR(64) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_samples_statuses_idx` (`status_id` ASC),
  INDEX `fk_samples_compute_nodes1_idx` (`compute_node_id` ASC),
  CONSTRAINT `fk_samples_statuses`
    FOREIGN KEY (`status_id`)
    REFERENCES `topmed_remapping`.`statuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_samples_compute_nodes1`
    FOREIGN KEY (`compute_node_id`)
    REFERENCES `topmed_remapping`.`compute_nodes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `topmed_remapping`.`job_executions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `topmed_remapping`.`job_executions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `start_date` DATETIME NOT NULL,
  `elapsed_seconds` INT UNSIGNED NOT NULL,
  `compute_node_id` VARCHAR(64) NOT NULL,
  `sample_id` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_job_executions_compute_nodes1_idx` (`compute_node_id` ASC),
  INDEX `fk_job_executions_samples1_idx` (`sample_id` ASC),
  CONSTRAINT `fk_job_executions_compute_nodes1`
    FOREIGN KEY (`compute_node_id`)
    REFERENCES `topmed_remapping`.`compute_nodes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_executions_samples1`
    FOREIGN KEY (`sample_id`)
    REFERENCES `topmed_remapping`.`samples` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `topmed_remapping`.`statuses`
-- -----------------------------------------------------
START TRANSACTION;
USE `topmed_remapping`;
INSERT INTO `topmed_remapping`.`statuses` (`id`, `name`) VALUES (DEFAULT, 'unprocessed');
INSERT INTO `topmed_remapping`.`statuses` (`id`, `name`) VALUES (DEFAULT, 'running-pre-align');
INSERT INTO `topmed_remapping`.`statuses` (`id`, `name`) VALUES (DEFAULT, 'failed-pre-align');
INSERT INTO `topmed_remapping`.`statuses` (`id`, `name`) VALUES (DEFAULT, 'pre-aligned');
INSERT INTO `topmed_remapping`.`statuses` (`id`, `name`) VALUES (DEFAULT, 'running-align');
INSERT INTO `topmed_remapping`.`statuses` (`id`, `name`) VALUES (DEFAULT, 'failed-align');
INSERT INTO `topmed_remapping`.`statuses` (`id`, `name`) VALUES (DEFAULT, 'aligned');
INSERT INTO `topmed_remapping`.`statuses` (`id`, `name`) VALUES (DEFAULT, 'running-post-align');
INSERT INTO `topmed_remapping`.`statuses` (`id`, `name`) VALUES (DEFAULT, 'failed-post-align');
INSERT INTO `topmed_remapping`.`statuses` (`id`, `name`) VALUES (DEFAULT, 'post-aligned');

COMMIT;

